# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hieu's blog
email: huynhtrunghieu.cs@gmail.com
description: This is a blog about Linux, Database, Infrastructure, some mathematics, and mindset.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://llnx.me" # the base hostname & protocol for your site
twitter_username:  
github_username: hieuhtr 

plugins: 
  - jekyll-paginate
  - jekyll-analytics

# jekyll-paginate     
paginate: 5

# jekyll-analytics
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-120893719-1      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
